-- ── option_snapshots ─────────────────────────────────────────────────────────
-- Intraday option chain snapshots. Written by market-refresh every 5 min
-- for all open-position tickers, 8 strikes OTM + 8 strikes ITM per side.
-- Purged after 90 days. ~8k rows/day for 10 tickers.

CREATE TABLE IF NOT EXISTS option_snapshots (
  id              bigserial PRIMARY KEY,
  symbol          text        NOT NULL,
  expiry          date        NOT NULL,
  strike          numeric     NOT NULL,
  opt_type        text        NOT NULL CHECK (opt_type IN ('call','put')),
  snapshot_at     timestamptz NOT NULL DEFAULT now(),
  dte             int,

  -- Option pricing
  bid             numeric,
  ask             numeric,
  mid             numeric,
  last            numeric,
  mark            numeric,

  -- Greeks
  iv              numeric,   -- implied volatility as % (e.g. 46.5)
  delta           numeric,
  gamma           numeric,
  theta           numeric,
  vega            numeric,

  -- Market data
  open_interest   int,
  volume          int,

  -- Stock context at time of snapshot
  stock_price     numeric     NOT NULL,
  stock_change_pct numeric,  -- % change from prior close
  otm_pct         numeric    -- positive = OTM, negative = ITM
);

-- Indexes for simulation queries
CREATE INDEX IF NOT EXISTS idx_option_snapshots_symbol_expiry
  ON option_snapshots (symbol, expiry, strike, opt_type, snapshot_at);

CREATE INDEX IF NOT EXISTS idx_option_snapshots_snapshot_at
  ON option_snapshots (snapshot_at);

-- Auto-purge handled in code (>90 days), but also define a helper view
-- for the last trading day's data
CREATE OR REPLACE VIEW option_snapshots_today AS
  SELECT * FROM option_snapshots
  WHERE snapshot_at >= CURRENT_DATE::timestamptz;


-- ── sim_results ───────────────────────────────────────────────────────────────
-- One row per simulated trade. Generated by simulate.js replaying
-- option_snapshots with different strategy parameters.

CREATE TABLE IF NOT EXISTS sim_results (
  id                  bigserial PRIMARY KEY,
  run_at              timestamptz NOT NULL DEFAULT now(),
  sim_label           text,        -- e.g. "2.5pct_OTM_65pct_target"

  symbol              text        NOT NULL,
  expiry              date        NOT NULL,
  strike              numeric     NOT NULL,
  opt_type            text        NOT NULL CHECK (opt_type IN ('call','put')),

  -- Entry conditions
  entry_at            timestamptz NOT NULL,
  entry_stock_price   numeric,
  entry_mid           numeric,
  entry_iv            numeric,
  entry_delta         numeric,
  entry_otm_pct       numeric,
  entry_dte           int,

  -- Exit conditions
  exit_at             timestamptz,
  exit_stock_price    numeric,
  exit_mid            numeric,
  exit_reason         text,       -- 'target_hit' | 'stop_hit' | 'expired_otm' | 'expired_itm' | 'eod'

  -- Outcome
  profit_per_contract numeric,    -- (entry_mid - exit_mid) * 100, negative = loss
  profit_pct          numeric,    -- profit_per_contract / (entry_mid*100) * 100
  won                 boolean,    -- profit_per_contract > 0

  -- Simulation parameters used (stored as jsonb for flexibility)
  sim_params          jsonb,
  -- e.g. { "otm_pct": 2.5, "target_pct": 65, "stop_pct": 200,
  --        "entry_time": "10:00", "dte_min": 1, "dte_max": 5 }

  -- Snapshot IDs for traceability
  entry_snapshot_id   bigint REFERENCES option_snapshots(id),
  exit_snapshot_id    bigint REFERENCES option_snapshots(id)
);

CREATE INDEX IF NOT EXISTS idx_sim_results_symbol
  ON sim_results (symbol, run_at);

CREATE INDEX IF NOT EXISTS idx_sim_results_label
  ON sim_results (sim_label, symbol);


-- ── sim_summary ───────────────────────────────────────────────────────────────
-- Aggregated results per sim_label + symbol. Updated by simulate.js after each run.

CREATE TABLE IF NOT EXISTS sim_summary (
  id              bigserial PRIMARY KEY,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  sim_label       text        NOT NULL,
  symbol          text        NOT NULL,

  -- Aggregate stats
  trade_count     int,
  win_count       int,
  win_rate        numeric,    -- 0-1
  avg_profit      numeric,    -- avg profit per contract in dollars
  avg_profit_pct  numeric,
  avg_loss        numeric,
  avg_loss_pct    numeric,
  ev              numeric,    -- expected value = (wr * avg_profit) + ((1-wr) * avg_loss)
  max_loss        numeric,
  max_profit      numeric,
  avg_dte_entry   numeric,
  avg_iv_entry    numeric,

  sim_params      jsonb,      -- params that generated this summary

  UNIQUE (sim_label, symbol)
);

CREATE INDEX IF NOT EXISTS idx_sim_summary_label
  ON sim_summary (sim_label);
